
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: rays.ray.kubeflow.org
spec:
  group: ray.kubeflow.org
  names:
    kind: Ray
    plural: rays
  scope: ""
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
